transforms:
  img_size: 224
  hflip: 0.
  vflip: 0.
  gscale: 0.
  rot_deg: 360
label:
  min: 5.0
  max: 12.22914799
pred:
  batch_size: 256
  smooth: 4
model:
  base_model:
    name: BaseModel
    model: ResNet18
    target_classes: 1
    final_activation: LeakyReLU
    rep:
      in_feats:
      - 384
n_gpus: 1
gpu_ids: 
  - 0
workers: 12
resume: trained_models/train/original_models/pain.pth
print_freq: 20
rng_seed: 0
task_type: regression
